### ISSUE TITLE
Use of Fahrenheit causes incorrect temperature readings

### ISSUE THREAD

**Issue by PSedd** [teodoradima/homebridge-samsung-air-conditioner-smart-things#1]
**Describe The Bug:**

Setting the device to Fahrenheit causes the plug in to assume it's in Celsius and convert. For example, my temperature in the living room is 70F, which is showing as 159F (it's assuming 70C).

**To Reproduce:**

Set device to Fahrenheit.

**Expected behavior:**

Expected temperature in Fahrenheit, not in Celsius (or F/C to F which seems to be happening). 

**Logs:**

```
[7/13/2021, 5:08:59 AM] [homebridge-samsung-air-conditioner-smart-things] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 70 exceeded maximum of 30. See https://git.io/JtMGR for more info.
```

**Plugin Config:**

```json
{
    "name": "homebridge-samsung-air-conditioner-smart-things",
    "token": "[REMOVED]",
    "platform": "HomebridgeSamsungACSmartThings"
}
```

**Screenshots:**

[Smart Things](https://imgur.com/a/v4TVQWT)
[Home App](https://imgur.com/a/h8aGMls)

**Environment:**

* **Plugin Version**:homebridge-samsung-air-conditioner-smart-things v1.0.3 
* **Homebridge Version**: 1.3.4
* **Node.js Version**:  14.17.2 
* **NPM Version**:  6.14.13 
* **Operating System**:  Ubuntu 20.04.2 Server

**Comment by irinel-nistor** [comment]
Hello, Thanks for pointing this issue out. Unfortunately we can't look into this until Sunday because we are not at home and we can't set our devices to F remotely, at least I couldn't find a way and it's difficult to test a potential fix.

**Comment by PSedd** [comment]
Oddly enough I can't find a way to set my devices to C in the app at all. I'll keep poking around and add any more information I come across until you get some time. Thanks!

**Comment by teodoradima** [comment]
Hi, @PSedd!

Could you, please, try version 1.0.4 and set the "temperatureUnit" parameter in the config to "F"?
Do let us know how it went and if you encounter any other issues.

**Comment by irinel-nistor** [comment]
When the config option temperatureUnit is set to F the temperature threshold is set between 60 F(~16 C) and 86 F(~30 C). Could you please confirm that this are the threshold values for your device?

**Comment by PSedd** [comment]
Hi all,
On the surface it looks like it's working, but there's still a few small issues. It reports the right temperature in HomeKit/HomeBridge, but when you get more info, it's still having some issues which I've attached in the screenshots below. 

Here's the message about the temp thresholds:
`[7/15/2021, 4:20:32 PM] [homebridge-samsung-air-conditioner-smart-things] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 21.11111111111111 exceeded minimum of 60. See https://git.io/JtMGR for more info.`

I wonder if that message is because I switched the SmartThings app (in web) to C. I'll revert back to F and see if it disappears (it seemed to take a day or so last time, so I'll let it bake for a bit)

Here's the detailed info in Home, which is showing the conversion issues still:
![1](https://user-images.githubusercontent.com/36494945/125831873-3779feb3-0526-49be-97b7-b43ea7d61ce0.jpg)


Here's the icon of all the AC's together, showing that they're cooling to 140 F:
![2](https://user-images.githubusercontent.com/36494945/125831964-eede6647-868e-429b-98ad-1298fa7c8fd9.jpg)

**Comment by irinel-nistor** [comment]
Hello @PSedd, I pushed another small fix, I'm expecting at least the cooling to value to show the correct value and not 140. As I said I can't test this properly because my device is set to C. Please let us know what other issues you encounter, I'm pretty sure you'll still have some warnings.

**Comment by PSedd** [comment]
Hi, 

The display is correct now, and I'm not getting any messages about the cooling value (which I'll just ignore anyway). The issue now is that when I set the temp and mode (Cooling & 75 F), it sets the temp to the lowest possible temp (61F ). One of the three AC's (Master Bedroom) shows as off after I adjust it in SmartThings, but the other two do not. 

I've attached some screenshots here to try and help. Is there a way to get a more verbose log to try and help further?

![1](https://user-images.githubusercontent.com/36494945/125983093-e1ab2fe8-e366-4e04-8e28-1a5ac80b7f7b.jpg)
![2](https://user-images.githubusercontent.com/36494945/125983101-ed190eb9-62c1-4493-82b4-9b819023cf41.jpg)
![3](https://user-images.githubusercontent.com/36494945/125983112-1abb2266-a65c-4666-8637-8e0bf910e880.jpg)

A super nitpicky thing (not sure it's possible to fix) is that the lighting options resets when adjusting via HomeKit. I usually have it off, but doing anything via HK/HB turns it on. Based of the limited features I'll assume it's not possible, but wanted to mention it to try and help development if possible.

**Comment by irinel-nistor** [comment]
Could you please show me any warnings you get when you try to set the temperature?

**Comment by PSedd** [comment]
Hi, no error messages or warnings in the HB console. In fact, outside of the "adding cached accessory" there's no entries in the logs at all. 

Noticed that temp is also supporting two degree temp differences (73+75, not 74). Not a big deal at all, thought it might help with some troubleshooting (assuming its not just doing a C conversion).

**Comment by irinel-nistor** [comment]
If you go to [Your account](https://account.smartthings.com/)  -> My devices -> specific air conditioner -> List events, can you maybe see any values the target temperature has been set with, is it 61? 
![image](https://user-images.githubusercontent.com/8067395/125988196-068d8f87-b6d2-4119-8f18-e11f05dba1de.png)

**Comment by PSedd** [comment]
There aren't any events listed in the last 5 hours, even when I change it via the SmartThings App. 
![1](https://user-images.githubusercontent.com/36494945/126011893-71359ae8-f4e3-4f81-9f2f-426899210710.PNG)


Additionally, I found this when starting the plugin this time:

[7/16/2021, 9:44:01 PM] ====================
[7/16/2021, 9:44:01 PM] ERROR LOADING PLUGIN homebridge-smartthings-ac:
[7/16/2021, 9:44:01 PM] Error: Cannot find module 'hap-nodejs/dist/lib/definitions'
Require stack:
- /usr/lib/node_modules/homebridge-smartthings-ac/dist/platformAccessory.js
- /usr/lib/node_modules/homebridge-smartthings-ac/dist/platform.js
- /usr/lib/node_modules/homebridge-smartthings-ac/dist/index.js
- /usr/lib/node_modules/homebridge/lib/plugin.js
- /usr/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/lib/node_modules/homebridge/lib/server.js
- /usr/lib/node_modules/homebridge/lib/cli.js
- /usr/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-smartthings-ac/src/platformAccessory.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
[7/16/2021, 9:44:01 PM] ====================

**Comment by irinel-nistor** [comment]
I tried another small fix, I've also added a log when the target temperature is set. Please update to the latest version and give it a go when you get a chance.

**Comment by PSedd** [comment]
Working great! There's still a gap in the degrees (75 ->73) but that's not something that bothers me, more of just an FYI in case it comes up again. 

Can confirm that I see `[7/17/2021, 8:49:43 PM] [homebridge-samsung-air-conditioner-smart-things] Set target temperature to: 24` when changing temperatures. Thanks so much!

**Comment by irinel-nistor** [comment]
The gap probably comes from the way I made the transformation from Fahrenheit to Celsius and viceversa. Basically you get F from Smartthings, the plugin turns it to C, then Homeapp turns it back to F (F->C->F). The same happens on setting the temperature, it's F in Homeapp it turns it to C and in the plugin we transform it back to F and send it to Smartthings (F->C->F). I'll look into what formula IOS(Homeapp) uses, probably if I'd use the exact same it wouldn't be a gap.

**Comment by irinel-nistor** [comment]
The gap is only between 73-75, meaning you can't set the temperature to 74? No other gaps?

**Comment by irinel-nistor** [comment]
Thanks for all your help, couldn't have braught it to this point without your help.

**Comment by PSedd** [comment]
I can set the temperature to: 61,63,64,66,68,70,72,73,75,77,79,81,82,84,86 in the Home app. After a bit of a spot check, it looks like its rounding (up or down) from a whole C. For example: 16C=60.8 rounding up to 61, 17C=62.6 rounding up to 63, 18C = 64.4 rounding down to 64 and so on.

Hope that helps, but it works fine as is, can't really notice 71 vs 72 and why F is stupid :)

**Comment by irinel-nistor** [comment]
Is it a problem with homekit? If you use the temperature wheel in homekit, can you pick one of the ones you mentioned 62, 71? If you still have version 1.0.7 of the plugin could you please let me know what values does it log, if you get a chance. I'm trying to understand if the problem comes from the formula I used. Thanks again!

**Comment by irinel-nistor** [comment]
If I think about it a bit more, It's impossible to solve, the range of C temperatures goes from 16 to 30 which is 14 values, the range of the F temperature goes from 61 to 86, which is 25 values. Mapping 25 values to 14 will only work if you have some gaps.

**Comment by irinel-nistor** [comment]
Unless values with decimals are accepted, If you still have the plugin with version 1.0.7 could you please let me know what values are logged when you set any of the values mentioned above or the ones that are missing? If all the values logged are integers there's nothing I can do, otherwise please give me as many values as you can.

**Comment by irinel-nistor** [comment]
This are the functions I'm using. I'm wondering if I should remove the rounding, but I'm not sure if HomeKit/IOS does the round up as well, that is why It would be helpful to get the logged temperature values
```
  private toCelsius(fTemperature) {
    return Math.round((5/9) * (fTemperature - 32));
  }

  private toFahrenheit(cTemperature){
    return Math.round((cTemperature * 1.8) + 32);
  }
```
